# Generated by Django 5.0.7 on 2024-08-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_chatroom_created_at_alter_chatroom_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='user1_language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='user2_language',
            field=models.CharField(default='en', max_length=10),
        ),
    ]
