# Generated by Django 5.0.7 on 2024-09-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_chatroom_user1_alter_chatroom_user1_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='task_state',
            field=models.CharField(default='start', max_length=20),
        ),
    ]
