# Generated by Django 5.0.7 on 2024-09-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='image_url',
        ),
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
            preserve_default=False,
        ),
    ]
