# Generated by Django 4.2 on 2024-10-08 19:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_remove_annotation_data_remove_annotation_geometry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='data',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
