# Generated by Django 4.2 on 2024-10-08 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_annotation_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='data',
        ),
    ]
