# Generated by Django 4.2 on 2024-10-09 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_remove_annotation_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='geometry',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
