# Generated by Django 4.2 on 2024-10-28 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_annotatedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='payment_code',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
