# Generated by Django 4.2 on 2024-11-10 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_chatroom_payment_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='payment_code_user2',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
