# Generated by Django 4.2 on 2024-11-10 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0019_chatroom_payment_code_user2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='payment_code_user2',
        ),
    ]
