# Generated by Django 4.2 on 2024-11-12 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0020_remove_chatroom_payment_code_user2'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='worker_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
