# Generated by Django 4.2 on 2024-11-25 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0021_chatroom_worker_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='campaign_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
