# Generated by Django 4.2 on 2024-11-25 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0022_chatroom_campaign_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroom',
            old_name='worker_id',
            new_name='user1_worker_id',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='campaign_id',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='payment_code',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='user1_campaign_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='user1_payment_code',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='user2_campaign_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='user2_payment_code',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='user2_worker_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
